### ISSUE TITLE
kernel_require.rb:126:in `require': cannot load such file -- pg_ext (LoadError)

### ISSUE THREAD

**Issue by joshco** [maxlapshin/mysql2postgres#74]
Any idea why this is happening?
$ mysqltopostgres taps/config.yml
````
c:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require':
cannot load such file -- pg_ext (LoadError)
        from c:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
        from c:/Ruby200/lib/ruby/gems/2.0.0/gems/mysqltopostgres-0.2.15/lib/mysqltopostgres.rb:7:in `<top (required)>'
        from c:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
        from c:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
        from c:/Ruby200/lib/ruby/gems/2.0.0/gems/mysqltopostgres-0.2.15/bin/mysqltopostgres:7:in `<top (required)>'
        from c:/Ruby200/bin/mysqltopostgres:23:in `load'
        from c:/Ruby200/bin/mysqltopostgres:23:in `<main>'
````

**Comment by paazmaya** [comment]
It seems to be an older version of this tool, and the given error relates to the PostgreSQL gem not found in the context.
It should be already fixed in the `master`, there is just not a release yet...

**Comment by joshco** [comment]
I tried it by building it from the git repo. version shows 0.2.20 and I'm still seeing the same issue.
Im running Ruby 2.0.0 on windows
My rails apps work just fine with postgres.

**Comment by jibiel** [comment]
`mysql2postgres` written in Ruby `1.9.3`. And `pg` gem [only specified for that platform](https://github.com/maxlapshin/mysql2postgres/blob/master/Gemfile#L15) at the moment:

```ruby
platforms :mri_19 do
  gem 'pg', '~> 0.17'
end
```

Just update platform to `:mri_20` or anything you want.
You can even put `gem 'pg'` outside of `platforms` block.

Then again
```bash
bundle install
gem build mysqltopostgres.gemspec
gem install mysqltopostgres-0.2.20.gem
```

**Comment by paazmaya** [comment]
@jibiel would you like to make a PR for that fox?

**Comment by jibiel** [comment]
@paazmaya You mean add the note to the dox or fix the `Gemfile`?

**Comment by paazmaya** [comment]
Change the `Gemfile`...

**Comment by jibiel** [comment]
That should it.

Also hard-coding ruby version with `ruby 1.9.3` in `Gemfile` is not very friendly for a public library too. Especially given that the most of the current users tries to build `gem` from source and `1.9.3` will be ancient tomorrow. I'd use `.ruby-version` file convention.

For that same reason it'd be nice to do CI testing against multiple ruby versions.

**Comment by paazmaya** [comment]
Thanks for the PR.
Would you like to work on the changes related to the Ruby version too?
